import { Game } from '../types';

export const games: Game[] = [
  {
    id: '1',
    title: 'eFootball',
    description: 'eFootball™ is a sports game developed by KONAMI. The APK has been available since May 2017. In the last 30 days, the app was downloaded about 6 million times. Its top ranked, its rated 3.89 out of 5 stars, based on 15 million ratings. The last update of the app was on June 5, 2025. eFootball™ has a content rating "Everyone" eFootball™ has an APK download size of 2.16 GB and the latest version available is 9.5.0. Designed for Android version 7.0+. eFootball™ is FREE to download.',
    icon:  'https://play-lh.googleusercontent.com/XBWeRnZvMwI1sUMbRD0q8OzKc6JHVog1XqOXmmbOHxPSG2hud17t8D5ojenwIZAsKvs',
    bannerImage: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1665460/921fc2c1953dfcb27cf31a845e4da4015c78edc7/capsule_616x353.jpg?t=1750996206',
    size: '1gb',
    rating: 4.2,
    downloads: '800K',
    tags: ['COINS', 'HACK'],
    category: 'game',
    featured: true,
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '2',
    title: 'Blood strike',
    description: 'Blood Strike is a battle royale game available on multiple platforms. With its fast-paced matches, smooth optimization and characters with distinctive abilities, the game has won the hearts of nearly 100 million players globally.',
    icon: 'https://img.utdstc.com/icon/00c/d22/00cd22f0cd7bb89a2af3dd0dfe72cfa03665e58e6135de63581c8c3ce5e61906:200',
    bannerImage: 'https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3199170/eeab00314314192f57bbdf91b91f8b871f890ce5/capsule_616x353.jpg?t=1748342194',
    size: '756mb',
    rating: 4.3,
    downloads: '850K',
    tags: ['GOLD', 'UNLOCKED'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '3',
    title: 'Delta Force',
    description: 'First Mobile Warfare: In All Out 24v24 Combat Experience never-seen-before modern wars on mobile in this epic All-Out Warfare. 48 players clash across land, sea, and air. Pilot a Black Hawk for air dominance, command a tank to break defenses, and unleash chaos with C4 or missile strikes. Everything is destructible—leave nothing standing.6 Warfare Maps, 6 Unique Modes, 100+ Weapons: Gear up and dominate! Or just blow it ALL up.',
    icon: 'https://assets-prd.ignimgs.com/2024/08/28/delta-force-button-replacement-1724855313566.jpg',
    bannerImage: 'https://cdn.theouterhaven.net/wp-content/uploads/2024/11/Gaming_DeltaForce_HawkOps_poster.jpg',
    size: '1gb',
    rating: 4.9,
    downloads: '2.1M',
    tags: ['COINS', 'MOD'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '4',
    title: 'Badoo',
    description: 'A popular app is Badoo Dating App: Meet & Date, which is highly ranked in several countries and, with over 100 million installs, is one of the most popular apps in Google Play.',
    icon: 'https://lh3.googleusercontent.com/60fSJCRSdOL2-ThkpzwbBJLHx4BAKq75KKYVTA9QVcudugU2mfk4nPfRLpx0t_E0fMmiwghsHYYrDG0rz6rthnVFvgGfzr0wR5_N=s96-rw',
    bannerImage: 'https://logos-world.net/wp-content/uploads/2022/06/Badoo-Logo.jpg',
    size: '20mb',
    rating: 4.7,
    downloads: '500k',
    tags: ['PREMIUM', 'HACKMOD'],
    category: 'app',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '5',
    title: 'Chikii',
    description: '※ Play games anytime and anywhere! Make your phone become a high-end game console on the go ※Most popular computer games all in Chikii! Every genre on Steam/Origin/Epic, updated weekly, no need to wait for mobile versions of your favorite games ※ No download, no installation! Just log in. Click Play; For all PC games, save mobile phone storage space; ※ VIP can play games for free! With a monthly subscription, you can play unpurchased games you with our VIP ※ Awesome game experience! Wonderful scenery, no lag, having your own game world without spending hundreds or thousands of dollars on PC games and consoles; ※ Online Multiplayer mode! Come and play computer games with your friends, and here is the advanced cloud game',
    icon: 'https://play-lh.googleusercontent.com/K_M78a6T2Th5ZPmtIYJ39kvDTGp9UEaRo9KVeH-5xsMUT_Fd9ACtP54MxdvURThqKms',
    bannerImage: 'https://cdn6.aptoide.com/imgs/6/8/a/68af8e6a9dafff1244af765e05aba409_fgraphic.png',
    size: '32mb',
    rating: 4.5,
    downloads: '500k',
    tags: ['UNLIMITED', 'HACK'],
    category: 'app',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '6',
    title: 'FrozenCach',
    description: 'The “FrozenCash” App is an entertaining and easy application to Make Money, Earn Prizes & Get Rewards, without experience, either by completing surveys or other methods... ▶ How do I earn or withdraw money? • To withdraw money or gift cards, you must collect the required pieces of ice, and to obtain it, there are several ways:  ▶ Completing surveys & offers. ▶ Sharing referral: • Share your referral code with friends and earn ice cubes for free.  ▶ Golden ticket code: • We share with our users a lot of Golden tickets code, to get free ice cube  ▶ Getting Red Cubes: • By sharing your referral code, you will get red cubes to spin the wheel & win fragments of ice cube. ▶ Withdrawal: • You can withdraw through many methods, including electronic wallets, games, and also recharge card codes...',
    icon: 'https://play-lh.googleusercontent.com/qoaueKu4iyXOAEIGVd24u_w9vzc0liN4-3lw_sDQOWI0EdDMG2jdeVlgqeDwWSYMkt4',
    bannerImage: 'https://t4.ftcdn.net/jpg/10/24/24/91/360_F_1024249124_0QqPnWrxlSJVhOpJu0WZH1D8iCqXzkXs.jpg',
    size: '67mb',
    rating: 4.5,
    downloads: '920K',
    tags: ['PREMIUM', 'POINTS'],
    category: 'app',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1'
  }
  ,
  // New Games
  {
    id: '7',
    title: 'Parchisi STAR Online',
    description: 'Parchisi STAR, played by millions of players worldwide is an online multiplayer version of popular classic board game Parchis. Parchis board game is a popular in Spain as Parchis and known by different name in other countries. It is a board game of the Cross and Circle family. It is an adaptation of the Indian game Pachisi or Parchis or Ludo or Parchis Online It is the ultimate rollercoaster, taking you from laughs to shouts in one intense match!',
    icon: 'https://play-lh.googleusercontent.com/dujhqfsabzHjJDYS4UYBXamOeI9E_LBfkxUtqNKPtCYj_7mEvuClAWq5YAQU33LaQRo',
    bannerImage: 'https://m.media-amazon.com/images/I/B1Y9zP6HjLS.png',
    size: '500mb',
    rating: 4.61,
    downloads: '700k',
    tags: ['GEMES'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '8',
    title: 'Bingo Blitz',
    description: 'oin millions of players in the best online free Bingo game in the world! Free daily Credits? Now THAT’s a Bingo! 😎 Experience your Bingo Moment, when everything comes together at once and it all feels just right! 🌟Enjoy exciting gameplay, endless content, an active social community, and free Bingo games! Join Blitzy the cat as he travels around the world, playing Bingo and making friends in every new place he visits',
    icon: 'https://play-lh.googleusercontent.com/00KV9KNRzXEx8e5AwlcKAQw2DvnlL2Sxc2WGyMS7NCKm_d_chxi16W7sHWYQ8biRww',
    bannerImage: 'https://i0.wp.com/edvardtoth.com/wp-content/uploads/2014/02/featured_bingoblitz.jpg?fit=800%2C533&ssl=1',
    size: '400mb',
    rating: 4.5,
    downloads: '400k',
    tags: ['CREDITS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '9',
    title: 'ZEPETO',
    description: 'ZEPETO is a social metaverse platform where users create and customize 3D avatars to explore virtual worlds, play games, and interact with others. Its a space for self-expression, creativity, and social connection, allowing users to personalize avatars, design items and worlds, and engage in real-time interactions',
    icon: 'https://play-lh.googleusercontent.com/EwN12x-sr1KVCpHYyG4kFE2NMH5ZdXStj5e5eHAFfyxNTcXRoUs4DxyJyvkBeeqY76k',
    bannerImage: 'https://web.zepeto.me/assets/img/im-default-og-new.png',
    size: '188mb',
    rating: 5.54,
    downloads: '150MB',
    tags: ['ZEMS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '10',
    title: 'One Piece Bounty Rush',
    description: 'Take the loot you pirate! One Piece Bounty Rush is a 3D anime battle arena treasure looting game set in the popular manga pirate world of One Piece! Join Luffy, the famous Straw Hat Pirate and all your favorite characters in 4 vs 4 real-time pvp battles to rush and loot the treasure of berry coins for victory!',
    icon: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/2918150/capsule_616x353.jpg?t=1749691413',
    bannerImage: 'https://play-lh.googleusercontent.com/_l5R_OyGejOrp6wR-eIhupblFEkm_7FXa-7aadQSldtNAUSC_3ob8CYDB-Z8ox7xmQ',
    size: '200mb',
    rating: 4.5,
    downloads: '1M',
    tags: ['DIAMOND'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '11',
    title: 'Hay Day',
    description: 'Hay Day is a free-to-play mobile farming simulation game where players build and manage their own farm, growing crops, raising animals, and producing goods. Players can expand their farm, trade with other players, and customize their farm with decorations. The game also features a town area where players can interact with various characters and complete tasks. ',
    icon: 'https://play-lh.googleusercontent.com/Za8u0ChNK-3mZ3rnLcBirRBTzLYTdqaaAn63Ha9qKZiDp_bF_5u7OGfvWb1dg88WttKw',
    bannerImage: 'https://www.u7buy.com/blog/wp-content/uploads/2024/03/hay-day.webp',
    size: '100mb',
    rating: 4.3,
    downloads: '300k',
    tags: ['DIAMOND'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '12',
    title: 'Yalla Ludo',
    description: 'Yalla Ludo is a mobile game app that combines the classic board games Ludo and Domino with real-time voice chat. It allows players to connect with friends and other players globally to play these games and chat simultaneously. The app offers various game modes and features, including team play, private rooms, and local rooms for offline play with friends. ',
    icon: 'https://play-lh.googleusercontent.com/qP-75o1OXuPSPIGNgsjkLzqaoqBGsFJlGGdTdtOiU3D5DeoL23W6R3CdDKsmAWOFMpQ',
    bannerImage: 'https://cdn6.aptoide.com/imgs/c/4/e/c4e24035fea13e9ea732ca145db3e1d7_fgraphic.png',
    size: '200mb',
    rating: 4.8,
    downloads: '500k',
    tags: ['DIAMOND'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '13',
    title: 'Zooba',
    description: 'ut this gameWelcome to Zooba, the ultimate brawl battle royale game where you become a star by battling against online players in an intense multiplayer shooting experience. Ready, set, frag, and fire your way to the top! 💥 Dominate the Zooba Arena and Become the Ultimate Shooting Star!',
    icon: 'https://play-lh.googleusercontent.com/ganz5FKN-8sFTBZ04hh-9unsONKdlmJ6yeV3bBgjTP95cfjahgcpI5MKZxsoFMfldag',
    bannerImage: 'https://nyxgameawards.com/upload/entry/files/NGE101519/25271691634481.jpg',
    size: '13mb',
    rating: 4.2,
    downloads: '500k',
    tags: ['GEMS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '14',
    title: 'Ludo Star',
    description: 'Ludo Star is a digital adaptation of the classic Ludo board game, allowing players to compete against friends, family, or random opponents online. It offers various game modes, including classic Ludo, Master, and Quick, along with options for 2-player, 4-player, or team-based matches. Players can log in with Facebook to connect with friends, chat, send gifts, and save their progress. The game also features voice chat, clubs for social interaction, and the ability to collect and unlock items',
    icon: 'https://i.pinimg.com/474x/35/89/8d/35898d4fc6666554b549401a59b32f4b.jpg',
    bannerImage: 'https://store-images.s-microsoft.com/image/apps.23512.14168906070567816.2c905c2f-df83-4ed1-b85a-8a30663f3138.0d912dd9-547b-4bf5-9039-f92dbc6c1e52?h=1280',
    size: '50mb',
    rating: 4.2,
    downloads: '400k',
    tags: ['GEMS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '15',
    title: 'Top War',
    description: 'Top War is a free-to-play mobile strategy game that combines merging and upgrading with real-time strategy elements. Players build and customize their bases, train armies, and battle online against other players worldwide. The game features a unique "merge to upgrade" mechanic, eliminating long wait times for upgrades by allowing players to instantly merge two units to upgrade them. ',
    icon: 'https://www.rivergame.net/comm/img/topwar_icon.jpg',
    bannerImage: 'https://cdn6.aptoide.com/imgs/f/b/8/fb87359c1ed4c5fd9cab52eff06ece1f_fgraphic.jpg',
    size: '100mb',
    rating: 3.8,
    downloads: '200k',
    tags: ['GEMS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '16',
    title: 'Monopoly GO',
    description: 'Monopoly Go is a mobile game that reimagines the classic board game Monopoly for digital play. Players roll dice, move around the board, buy properties, and build landmarks. The game also includes social elements, allowing players to connect with friends, participate in co-operative events, and even "wreck" each others boards. Monopoly Go features various themed boards, mini-games, and sticker collections to enhance the gameplay.',
    icon: 'https://m.media-amazon.com/images/I/81Iaj1F8MxL.png',
    bannerImage: 'https://blog.en.uptodown.com/files/2023/05/monopolygo.jpg',
    size: '100mb',
    rating: 4.8,
    downloads: '800k',
    tags: ['DICE'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '17',
    title: '8 Ball Pool',
    description: '8-ball pool is a popular cue sport where two players compete to pocket all of their designated balls (either solids or stripes) and then legally pocket the 8-ball to win. Its played on a rectangular table with six pockets, using a cue ball and 15 object balls. The object balls are divided into two groups: solids (1-7) and stripes (9-15)',
    icon: 'https://m.media-amazon.com/images/I/81OMgLAhLCL.png',
    bannerImage: 'https://gamesbymanuel.com/wp-content/uploads/2014/07/8bp_header.jpg?w=1100',
    size: '200mb',
    rating: 4.8,
    downloads: '500k',
    tags: ['COINS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '18',
    title: 'PUBG Mobile',
    description: 'PUBG Mobile is a free-to-play, online multiplayer battle royale game where up to 100 players parachute onto an island, scavenge for weapons and equipment, and fight to be the last person or team standing. Its a mobile adaptation of the popular PC and console game, PUBG: Battlegrounds. The game features various maps, modes, and weapon choices, offering a diverse and engaging experience for players.',
    icon: 'https://play-lh.googleusercontent.com/zCSGnBtZk0Lmp1BAbyaZfLktDzHmC6oke67qzz3G1lBegAF2asyt5KzXOJ2PVdHDYkU',
    bannerImage: 'https://web9academy.com/wp-content/uploads/2024/11/SADG6MgH-PUBGMobile-1-1-1200x675-1.jpg',
    size: '500mb',
    rating: 4.8,
    downloads: '500k',
    tags: ['UC'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '19',
    title: 'Free Fire',
    description: 'Free Fire is a free-to-play, mobile battle royale game where 50 players parachute onto an island and fight to be the last one standing. Players scavenge for weapons and supplies, and a shrinking safe zone forces them into close-quarters combat. The game features various maps, characters with unique abilities, and both Battle Royale and Clash Squad modes.',
    icon: 'https://play-lh.googleusercontent.com/sKh_B4ZLfu0jzqx9z98b2APe2rxDb8dIW-QqFHyS3cpzDK2Qq8tAbRAz3rXzOFtdAw',
    bannerImage: 'https://cdn12.idcgames.com/storage/image/1258/free-new-logo/default.jpg',
    size: '500mb',
    rating: 4.6,
    downloads: '500K',
    tags: ['DIAMOND'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '20',
    title: 'FC Mobile 25',
    description: '',
    icon: 'https://play-lh.googleusercontent.com/Y9b4eFdmIVxCSX1nkcVTanNQf8Xwwi8Sw9dugY5ttHCKaWJ0p-Rmdvd-yv6FNm9vSGs',
    bannerImage: 'https://img.utdstc.com/screen/2f5/c0b/2f5c0b7f87d8389fc6552349902562505f8cd223a532b6383fe839eac16ae20d:600',
    size: '500mb',
    rating: 4.8,
    downloads: '700k',
    tags: ['FC POINT','FC COINS'],
    category: 'game',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  // New Apps
  {
    id: '21',
    title: 'ClipClaps',
    description: '',
    icon: 'https://cdn6.aptoide.com/imgs/4/e/e/4eeb655de61de41d48356f1e59144023_icon.png',
    bannerImage: 'https://cdn6.aptoide.com/imgs/e/a/e/eae658cc13191d3c04c597a8a23df31b_fgraphic.png',
    size: '50mb',
    rating: 3.8,
    downloads: '',
    tags: ['HACK','MOD'],
    category: 'app',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  },
  {
    id: '22',
    title: 'Tango',
    description: '',
    icon: 'https://play-lh.googleusercontent.com/ezjWRoLxhX85goIwrSx2aPYDLvybt63jI83vvNab714sVZAA3wdNNUZN8-vvoDSCwBE',
    bannerImage: 'https://cdn.prod.website-files.com/67dd87a09a0df218fdc114d3/67dd87a09a0df218fdc1274b_CEO%20Blog%20Post%20Cover%402x.avif',
    size: '80mb',
    rating: 3.9,
    downloads: '100k',
    tags: ['MOD','HACK'],
    category: 'app',
    downloadUrl: 'https://d2jgih9urxpa47.cloudfront.net/public/locker.php?it=4268398&key=c7e1c'
  }
];